<a href="https://colab.research.google.com/github/PoulavBhowmick03/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

In [2]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,7,0]],
                       [[1,2,3],
                        [3,6,9],
                        [4,7,0]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 7, 0]],

        [[1, 2, 3],
         [3, 6, 9],
         [4, 7, 0]]])

In [3]:
TENSOR.ndim

3

In [4]:
TENSOR.shape

torch.Size([2, 3, 3])

In [5]:
TENSOR[1]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 7, 0]])

#Random Tensors


In [6]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4082, 0.3670, 0.2484, 0.5086],
        [0.9585, 0.3255, 0.8307, 0.5978],
        [0.0706, 0.0039, 0.4820, 0.2122]])

In [7]:
random_image_tensor = torch.rand(224,224,3) #height, widthm, color channels (R,G,B)
random_image_tensor.shape


torch.Size([224, 224, 3])

In [8]:
## Zeroes and Ones
#All zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Tensor Datatypes

In [12]:
float_32_tensor = torch.tensor([3.0,6.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)