<a href="https://colab.research.google.com/github/PoulavBhowmick03/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

In [2]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,7,0]],
                       [[1,2,3],
                        [3,6,9],
                        [4,7,0]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 7, 0]],

        [[1, 2, 3],
         [3, 6, 9],
         [4, 7, 0]]])

In [3]:
TENSOR.ndim

3

In [4]:
TENSOR.shape

torch.Size([2, 3, 3])

In [5]:
TENSOR[1]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 7, 0]])

#Random Tensors


In [6]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4941, 0.0082, 0.7599, 0.9262],
        [0.6719, 0.4741, 0.1025, 0.8121],
        [0.7428, 0.8192, 0.8411, 0.8686]])

In [7]:
random_image_tensor = torch.rand(224,224,3) #height, widthm, color channels (R,G,B)
random_image_tensor.shape


torch.Size([224, 224, 3])

In [8]:
## Zeroes and Ones
#All zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Tensor Datatypes

In [10]:
float_32_tensor = torch.tensor([3.0,6.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

In [11]:
#Manipulating Tensors (tensor operations)

# 1. Addition
# 2. Subs
# 3. Multiply
# Division
# Matrix multiply

random_tensor1 = torch.rand(4,4)
random_tensor2 = torch.rand(4,4)
tensor_mult = torch.matmul(random_tensor1, random_tensor2)
random_tensor1, random_tensor2 ,random_tensor1 + random_tensor2,random_tensor1 - random_tensor2 ,  tensor_mult

(tensor([[0.1670, 0.1437, 0.9091, 0.6455],
         [0.7614, 0.1822, 0.0990, 0.0740],
         [0.6636, 0.4659, 0.7117, 0.7757],
         [0.8049, 0.8281, 0.4774, 0.1450]]),
 tensor([[0.4885, 0.9526, 0.5421, 0.3507],
         [0.3824, 0.8869, 0.8390, 0.1686],
         [0.3730, 0.6315, 0.5773, 0.5431],
         [0.2679, 0.5223, 0.4678, 0.3194]]),
 tensor([[0.6554, 1.0963, 1.4511, 0.9962],
         [1.1439, 1.0691, 0.9380, 0.2425],
         [1.0366, 1.0974, 1.2890, 1.3188],
         [1.0728, 1.3503, 0.9451, 0.4644]]),
 tensor([[-0.3215, -0.8089,  0.3670,  0.2948],
         [ 0.3790, -0.7048, -0.7401, -0.0946],
         [ 0.2907, -0.1656,  0.1344,  0.2326],
         [ 0.5370,  0.3058,  0.0096, -0.1743]]),
 tensor([[0.6485, 1.1977, 1.0378, 0.7827],
         [0.4983, 0.9880, 0.6573, 0.3751],
         [0.9756, 1.8999, 1.5243, 0.9456],
         [0.9267, 1.8784, 1.4745, 0.7275]]))

# Reshaping, stacking and squeezing tensors
* Reshape= reshapes to a defined shape
* View = return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stack = combines multiple tensors on top of each other (vstack) or side by side (hstack)

In [12]:
import torch
x= torch.arange(1. ,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

#Pytorch Tensors and Numpy
*Numpy to Torch tensor -> torch.from_numpy(ndarray)

*Torch tensor to Numpy -> torch.Tensor()

In [14]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [15]:
#change the value of array
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [16]:
#Tensor to Numpy
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [17]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:
`start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data -> again -> again -> again`

Howver, to reduce randomness in NN and pytorch, comes the concept of
**random seed**
Essen

In [18]:
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)

print(random_tensorA==random_tensorB)

tensor([[0.0100, 0.7046, 0.0138, 0.9015],
        [0.3403, 0.2803, 0.3959, 0.8713],
        [0.3319, 0.8325, 0.7858, 0.5498]])
tensor([[0.8368, 0.0325, 0.6288, 0.5007],
        [0.9513, 0.0152, 0.2259, 0.1740],
        [0.2079, 0.1426, 0.8620, 0.1860]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [19]:
#Random but reproducibkle tensors
import torch

#Set the Random seed
RANDOM_SEED = 22
torch.manual_seed(RANDOM_SEED)

random_tensorC= torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensorD= torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC==random_tensorD)

tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [20]:
#Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [21]:
tensor = torch.tensor ([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [22]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#Moving tensor back to cpu


In [23]:
#To fix GPU tensor to numpy, set it to cpu
tensor_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_to_cpu


array([1, 2, 3])

# Pytorch Workflow